
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret: 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
            scope:
              - email
              - profile

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

